### ISSUE TITLE
spring cors does not setup properly

### ISSUE THREAD

**Issue by luvlee-liu** [gothinkster/spring-boot-realworld-example-app#1]
run with https://github.com/gothinkster/react-redux-realworld-example-app
get follow error in chrome console

> Failed to load http://localhost:8080/api/user: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4100' is therefore not allowed access. The response had HTTP status code 401.

**Comment by aisensiy** [comment]
This is an issue mentioned in [https://github.com/spring-projects/spring-boot/issues/5834](https://github.com/spring-projects/spring-boot/issues/5834). Already fixed it. 😃
