### ISSUE TITLE
Extra collection of tags into Set

### ISSUE THREAD

**Issue by kebritam** [gothinkster/spring-boot-realworld-example-app#31]
[https://github.com/gothinkster/spring-boot-realworld-example-app/blob/master/src/main/java/io/spring/core/article/Article.java] Article

`core.article` package in `Article `class constructor, you have collected `Tag`s in the `Set` then immediately collected them into a `List`.
Is there a good reason for that? If it's for shuffling, it's better to use `Collections.shuffle()`.

**Comment by Donquih0te** [comment]
I think that did for removing duplicates
