### ISSUE TITLE
Missing or nolicense

### ISSUE THREAD

**Issue by tjozsa** [gothinkster/spring-boot-realworld-example-app#33]
Can you please include your chosen LICENSE.md file. I can't legally use your work unless you allow me to. I think it is only fair to assume that you wanted to publish this work with the same MIT license that you used on the realworld.io repo (https://github.com/gothinkster/realworld).

**Comment by aisensiy** [comment]
https://github.com/gothinkster/spring-boot-realworld-example-app/blob/master/LICENSE added.
