### ISSUE TITLE
Could not find snakeyaml-1.27-android.jar (org.yaml:snakeyaml:1.27)

### ISSUE THREAD

**Issue by vmihailenco** [gothinkster/spring-boot-realworld-example-app#34]
```bash
./gradlew bootJar

* What went wrong:
Execution failed for task ':bootJarMainClassName'.
> Could not find snakeyaml-1.27-android.jar (org.yaml:snakeyaml:1.27).
  Searched in the following locations:
      file:/home/vmihailenco/.m2/repository/org/yaml/snakeyaml/1.27/snakeyaml-1.27-android.jar
```

Adding the v1.28 as a dependency to build.gradle fixes the problem for me

```
implementation 'org.yaml:snakeyaml:1.28'
```

Googling [says](https://github.com/DiUS/java-faker/issues/327) that this is caused by incorrect classifier (android) in 1.27 version...

**Comment by aisensiy** [comment]
I don't have this issue and this app also successfully deployed in [heroku](https://realworld-java.herokuapp.com/graphiql). Just try to reinstall your dependencies.

**Comment by hioymaci** [comment]
I have also same problem and importing snakeyaml dependency is not working.

**Comment by edwincabezas7** [comment]
same situation, thanks, it works for me: rm -rf /Users/xxxxxxxxx/.m2/repository/org/yaml/snakeyaml/1.23
