### ISSUE TITLE
Login mutation doesn't work

### ISSUE THREAD

**Issue by adil-waqar** [gothinkster/spring-boot-realworld-example-app#35]
If I use the login mutation under `UserMutation`, it works fine. But protected mutations like `createArticle` still don't work, throwing Authentication exception. The code itself also doesn't send out a JWT token on login. What could be the issue?

**Comment by aisensiy** [comment]
You should add `Authentication Header`  for those requests:

![image](https://user-images.githubusercontent.com/661860/131966018-ed6ad0a8-6ef4-45be-8c34-6aa34c77b654.png)

**Comment by adil-waqar** [comment]
> You should add `Authentication Header` for those requests:
> 
> ![image](https://user-images.githubusercontent.com/661860/131966018-ed6ad0a8-6ef4-45be-8c34-6aa34c77b654.png)

And where do I get the Authorization token from? Login doesn't return it

**Comment by aisensiy** [comment]
![image](https://user-images.githubusercontent.com/661860/132177385-f084c28c-c0ef-4928-8823-0c44c1f3c2a6.png)

**Comment by adil-waqar** [comment]
> ![image](https://user-images.githubusercontent.com/661860/132177385-f084c28c-c0ef-4928-8823-0c44c1f3c2a6.png)
> 
> I think the schema shows the message :-)

My bad, totally missed that. Thanks!
