### ISSUE TITLE
Error With Getter and setter 

### ISSUE THREAD

**Issue by thornsereyvong** [gothinkster/spring-boot-realworld-example-app#4]

**Comment by aisensiy** [comment]
I use Lombok which need support in IDE. Check [https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000224490-IntelliJ-IDEA-Lombok-Not-Working](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000224490-IntelliJ-IDEA-Lombok-Not-Working) for some help.

**Comment by AbhishekAnand24** [comment]
I have also faced the same issue while using Lombok  in eclipse.

And I am able to solve the issue by following the below steps.

1.Copy and paste the lombok jar into the eclipse installation folder.
2.Run the command "java -jar lombok-.jar".
3.A GUI opens.
4.Check the IDE listed in the installer.
5.This entry should be available in the eclipse.ini file "-javaagent:<>".
6.Restart Eclipse to find the changes which starts listing the associated getters, setters in your java file.

Hope this will help you.
