### ISSUE TITLE
401 error on login

### ISSUE THREAD

**Issue by masithedeveloper** [gothinkster/spring-boot-realworld-example-app#5]
I get a 401 error code when logging in, how do I use the JWT secret key provided in application.properties file?

**Comment by aisensiy** [comment]
How do you get the jwt token? I think this should works with the official frontend application.

**Comment by darioseidl** [comment]
I was wondering the same at first. I got it running like this:
* edit `application.properties` and add `spring.h2.console.enabled=true` to enable the h2 console
* edit `WebSecurityConfig.java` and add the following lines to the `configure` method to allow access to the h2 console:
```
.antMatchers("/h2-console", "/h2-console/**")
            .permitAll()
```
(before `.anyRequest().authenticated()`)
and
```
.and()
            .headers().frameOptions().sameOrigin();
```
(after `.anyRequest().authenticated()`)
* run with `./gradlew bootRun`
* access the h2 console at `http://localhost:8080/h2-console` and create a new user
* login with email and password from the new user with a JSON POST `http://localhost:8080/users/login` with body ```{"user":{"email":"{{EMAIL}}", "password":"{{PASSWORD}}"}}```
(not `/api/users/login`)

Voila, you get the user with the JWT in the body!

**Comment by aisensiy** [comment]
@darioseidl so you are using the official frontend to access `/users/login` or from the backend api?

**Comment by darioseidl** [comment]
I haven't tried any frontend yet. I was just running the backend and using the Postman collection from https://github.com/gothinkster/realworld/tree/master/api

**Comment by aisensiy** [comment]
So this is done with [https://github.com/gothinkster/spring-boot-realworld-example-app/pull/6](https://github.com/gothinkster/spring-boot-realworld-example-app/pull/6)?
