### ISSUE TITLE
HTTP ERROR 401

### ISSUE THREAD

**Issue by pjBooms** [gothinkster/spring-boot-realworld-example-app#9]
With
```
./gradlew bootRun
open http://localhost:8080
```
I get "HTTP ERROR 401" in the browser.
What do I do wrong?

**Comment by tqiqgq** [comment]
I have a this problem. Set full access - dont work(

**Comment by aisensiy** [comment]
The `/` need authentication by default. See the access strategy in [WebSecurityConfig.java](https://github.com/gothinkster/spring-boot-realworld-example-app/blob/master/src/main/java/io/spring/api/security/WebSecurityConfig.java).
